name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Dependencies
        run: npm ci

      - name: Create release pull request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release (MacOS arm64)
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./flow_typescript_tools_Darwin_arm64.tar.gz
          asset_name: flow_typescript_tools_v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}_Darwin_arm64.tar.gz
          tag: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          overwrite: true

      - name: Upload binaries to release (MacOS x86_64)
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./flow_typescript_tools_Darwin_x86_64.tar.gz
          asset_name: flow_typescript_tools_v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}_Darwin_x86_64.tar.gz
          tag: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          overwrite: true

      - name: Upload binaries to release (Windows x86_64)
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./flow_typescript_tools_Windows_x86_64.tar.gz
          asset_name: flow_typescript_tools_v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}_Windows_x86_64.tar.gz
          tag: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          overwrite: true

      - name: Upload binaries to release (Linux x86_64)
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./flow_typescript_tools_Linux_x86_64.tar.gz
          asset_name: flow_typescript_tools_v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}_Linux_x86_64.tar.gz
          tag: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          overwrite: true
